# Generated by Django 2.2.4 on 2019-11-29 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PwKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128)),
                ('key_owner', models.CharField(max_length=64)),
                ('alliance_officer', models.BooleanField(default=False)),
                ('valid', models.BooleanField(default=True)),
                ('limited', models.BooleanField(default=False)),
            ],
        ),
    ]
